apiVersion: v2
name: traefik
description: A Traefik based Kubernetes ingress controller
type: application
version: 2.8.4
keywords:
  - traefik
  - ingress
home: https://traefik.io/
sources:
  - https://github.com/traefik/traefik
  - https://github.com/traefik/traefik-helm-chart
icon: https://raw.githubusercontent.com/traefik/traefik/v2.3/docs/content/assets/img/traefik.logo.png
dependencies:
  - name: traefik
    version: "26.0.0"
    repository: '@traefik'