apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: le-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.pathmatcher: PathPrefix
  name: vaultwarden-baylabs
  namespace: vaultwarden
spec:
  ingressClassName: traefik
  rules:
  - host: warden.baylabs.dev
    http:
      paths:
      - backend:
          service:
            name: vaultwarden-vaultwarden
            port:
              number: 8080
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - warden.baylabs.dev
    secretName: tls-secret-baylabs
